name: test
on: 
  push:
    branches:
      - develop
jobs:
  build:
    steps:
      - name: dotnet build
        uses: docker://mcr.microsoft.com/dotnet/core/sdk:3.1
      - name: info
        run: dotnet --info
      