name: test
on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: 1
          MYSQL_DATABASE: dac
          MYSQL_USER: dac
          MYSQL_PASSWORD: dac
        ports:
          - "3306:3306"
      postgres:
        image: postgres
        env:
          POSTGRES_USER: dac
          POSTGRES_PASSWORD: dac
          POSTGRES_DB: dac
        ports:
          - "5432:5432"
      mssql:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "!Passw0rd"
        ports:
          - "1433:1433"  
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
      - name: info
        run: dotnet --info
      - name: ls
        run: ls -la
      - name: test
        run: dotnet test
      